language: c
jobs:
  include:
  - os: linux
    arch: arm64
    dist: bionic
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    osx_image: xcode10.1
  - os: osx
    osx_image: xcode11.3
script:
  - .ci/script.sh
