language: c
jobs:
  include:
    - name: test/win
      os: windows
      compiler: msvc
      env:
        - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/14.0/Bin"
      before_install:
        - export PATH="$MSBUILD_PATH:$PATH"
      install:
        - choco install -y visualstudio2017community visualstudio2017-workload-nativecrossplat
        - choco install visualstudio2017-workload-vctools -y
script:
  - .ci/script.sh
