language: c
jobs:
  include:
    - name: aarch64 / arm minimal tests
      os: linux
      arch: arm64
      dist: bionic
    - name: gcc 5.4 / full tests
      os: linux
      compiler: gcc
    - name: gcc 7 / full tests / OPAM package install
      dist: bionic
      install:
        - sudo apt update -q --yes && sudo apt install opam -q --yes
        - opam init --yes
        - eval $(opam config env)
        - opam install --yes ctypes ctypes.foreign dune
    - name: clang 7 / full tests
      os: linux
      compiler: clang
    - name: xcode 10 / full tests
      os: osx
      osx_image: xcode10.1
    - name: xcode 11 / full tests
      os: osx
      osx_image: xcode11.3
script:
  - .ci/script.sh
