language: c
jobs:
  include:
  - os: linux
    arch: arm64
    dist: bionic
  - os: linux
    dist: bionic
    compiler:
      - clang
      - gcc
  - os: osx
    compiler:
      - clang
      - gcc
    script:
      - brew install openssl
      - export CFLAGS="-I/usr/local/Cellar/openssl@1.1/1.1.1d/include/"
      - export LDFLAGS="-L/usr/local/Cellar/openssl@1.1/1.1.1d/lib"
script:
  - cd dist/gcc-compatible && ./configure
  - make -j
  - if [ "$(uname -m | cut -c 1-7)" == "aarch64" ]; then make -C ../../tests arm -j; else make -C ../../tests -j test; fi
