language: c
jobs:
  include:
    - name: test/win
      os: windows
      compiler: msvc
      env:
        - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/14.0/Bin"
      before_install:
        - export PATH="$MSBUILD_PATH:$PATH"
      install:
        - cl *.c
script:
  - .ci/script.sh
