language: c
jobs:
  include:
    - name: test/win
      os: windows
      compiler: msvc
      env:
        - MATRIX_EVAL="CC=cl.exe && CXX=cl.exe"
      before_install:
        - eval "${MATRIX_EVAL}"
      install:
        - choco install ninja
      script:
        - mkdir build && cd build
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release &&
          ninja -v'
        - ctest -V
script:
  - .ci/script.sh
