language: c
jobs:
  include:
  - os: linux
    arch: arm64
    dist: bionic
  - os: linux
  - os: osx
    osx_image: xcode10.1
  - os: osx
    osx_image: xcode11.3
script:
  - for p in /usr/local/Cellar/openssl@1.1/*; do export CFLAGS="-I$p/include/"; export LDFLAGS="-L$p/lib"; done
  - cd dist/gcc-compatible && ./configure
  - make -j
  - if [ "$(uname -m | cut -c 1-7)" == "aarch64" ]; then make -C ../../tests arm -j; else make -C ../../tests -j test; fi
  - cd ../test/c/
  - git clone https://github.com/fstarlang/kremlin -b protz_ci --depth 10
  - make -C kremlin/dist/kremlib/generic -f Makefile.basic
  - export KREMLIN_HOME=$(pwd)/kremlin
  - make -j
